[build]
command = "CI='' npm run build"
publish = "/build"
base = "/"

[functions]
directory = "netlify/functions"

[dev]
port = 8888
targetPort = 3000

[[redirects]]
from = "/api/v1/hdfc/create-session"
to = "/.netlify/functions/hdfc-create-session"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
